src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EvenementRepository::class)]
class Evenement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 255)]
    private ?string $lieux = null;

    #[ORM\ManyToOne(inversedBy: 'evenements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $id_createur = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\OneToMany(mappedBy: 'evenement', targetEntity: Inscription::class, orphanRemoval: true)]
    private Collection $inscriptions;

    public function __construct()
    {
        // Initialisez le champ $photo avec la valeur par défaut
        $this->image = '400.svg';
        $this->inscriptions = new ArrayCollection(); 
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getLieux(): ?string
    {
        return $this->lieux;
    }

    public function setLieux(string $lieux): static
    {
        $this->lieux = $lieux;

        return $this;
    }

    public function getIdCreateur(): ?User
    {
        return $this->id_createur;
    }

    public function setIdCreateur(?User $id_createur): static
    {
        $this->id_createur = $id_createur;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Inscription>
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): static
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions->add($inscription);
            $inscription->setEvenementId($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): static
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getEvenementId() === $this) {
                $inscription->setEvenementid(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EventMakerType;
use App\Form\EventEditType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\EvenementRepository;
use App\Repository\InscriptionRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Controller\EvenementController;
use App\Form\DateFilterType;
use DateTime;
use Doctrine\ORM\Mapping\OrderBy;

class HomeController extends AbstractController
{

    private $evenementController;

    public function __construct(EvenementController $evenementController)
    {
        $this->evenementController = $evenementController;
    }

    #[Route('/', name: 'app_home')]
    public function index(EvenementRepository $evenementRepository, Request $request, EntityManagerInterface $manager): Response
    {

        $today = new DateTime();

        $upcomingEvents = $evenementRepository->createQueryBuilder('e')
            ->where('e.date_debut >= :today')
            ->setParameter('today', $today)
            ->OrderBy('e.date_debut', 'ASC')
            ->getQuery()->getResult();
            
        $dateFilterForm = $this->createForm(DateFilterType::class);
        $dateFilterForm-> handleRequest($request);

        $startDate = null;
        $endDate = null;

        if ($dateFilterForm->isSubmitted() && $dateFilterForm->isValid()) {
            $data = $dateFilterForm->getData();
            $startDate = $data['startDate'];
            $endDate = $data['endDate'];
        }

        $filteredEvents = $evenementRepository->findEventsInDateRange($startDate, $endDate);
        // trie par ordre chronologique
        usort($filteredEvents, function ($a, $b) {
            return $a->getDateDebut() <=> $b->getDateDebut();
        });

        return $this->render('home/index.html.twig', [
            'filteredEvents' => $filteredEvents,
            'dateFilterForm' => $dateFilterForm->createView(),
            'evenements' => $upcomingEvents // $evenementRepository->findBy([], ['date_debut' => 'ASC']),
        ]);
    }

    #[Route('/createEvent', name: 'app_createEvent')]
    public function createEvent(Request $request, EntityManagerInterface $manager): Response
    {
        $user = $this->getUser();
        $event = new Evenement();

        $form = $this->createForm(EventMakerType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('image')->getData();    
                // Vérifiez si un fichier a été téléchargé
            if ($imageFile) {
                // Générez un nom de fichier unique
                $newFilename = uniqid().'.'.$imageFile->guessExtension();

                // Déplacez le fichier vers un répertoire le stockage 
                $imageFile->move(
                    $this->getParameter('image_directory'),
                    $newFilename
                );
                // Mettez à jour la propriété de l'entité avec le nom du fichier
                $event->setImage($newFilename);
            }

            $event = $form->getData();
            $event->setIdCreateur($user);
            $manager->persist($event);
            $manager->flush();

            $this->addFlash(
                'success', 
                'Votre évènement a bien été créé.'
            );

            return $this->redirectToRoute(('app_createEvent'));
        }

        return $this->render('home/eventMaker.html.twig', [
            'form' =>  $form->createView()
        ]);
    }

    #[Route('/showEvent/{evenementId}', name: 'app_showEvent')]
    public function showEvent(Request $request, EvenementRepository $evenementRepository, $evenementId): Response
    {
        $routeName = $request->query->get('routeName');
        $previousRouteName = $routeName;


        return $this->render('home/showEvent.html.twig', [
            'previousRouteName' => $previousRouteName,
            'routeName' => $routeName,            
            'evenement' => $evenementRepository->find($evenementId),
        ]);
    }

    #[Route('/editEvent/{evenementId}', name: 'app_editEvent')]
    public function editEvent(EvenementRepository $evenementRepository, Request $request, EntityManagerInterface $manager, $evenementId): Response
    {
        $routeName = $request->query->get('routeName');
        $previousRouteName = $routeName;

        $user = $this->getUser();
        $event = $evenementRepository->find($evenementId);
        $form = $this->createForm(EventEditType::class, $event);
        // dd($form);
        $event->setIdCreateur($user);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('image')->getData();    
                    // Vérifiez si un fichier a été téléchargé
            if ($imageFile) {
                // Générez un nom de fichier unique
                $newFilename = uniqid().'.'.$imageFile->guessExtension();

                // Déplacez le fichier vers un répertoire le stockage 
                $imageFile->move(
                    $this->getParameter('image_directory'),
                    $newFilename
                );
                // Mettez à jour la propriété de l'entité avec le nom du fichier
                $event->setImage($newFilename);
            }

            $event = $form->getData();
            $manager->persist($event);
            $manager->flush();

            $this->addFlash(
                'success', 
                'Votre évènement a bien été modifié.'
            );



            return $this->redirectToRoute($routeName);
        }



        return $this->render('home/editEvent.html.twig', [
            'previousRouteName' => $previousRouteName,
            'routeName' => $routeName,       
            'evenement' => $evenementRepository->find($evenementId),
            'form' => $form->createView(),
        ]);
    }

    #[Route('/deleteEvent/{evenementId}', name: 'app_deleteEvent')]
    public function deleteEvent(EvenementRepository $evenementRepository, Request $request, EntityManagerInterface $manager, $evenementId): Response
    {
        $user = $this->getUser();     
        $evenement = $evenementRepository->findOneBy([
            'id' => $evenementId,            
            'id_createur' => $user
        ]);
        $manager->remove($evenement);
        $manager->flush();

        $this->addFlash('success', 'Cet événement a bien été supprimer.');
        $routeName = $request->query->get('routeName');
        return $this->redirectToRoute($routeName);
    }

    #[Route('/MyEvent', name:'app_myEvent')]
    public function myEvent(Request $request, EvenementRepository $evenementRepository): Response 
    {
        $user = $this->getUser();
        $evenements = $evenementRepository->findBy(['id_createur' => $user]);
            
        return $this->render('home/myRegistration.html.twig', [
            'evenements' => array_reverse($evenements),
        ]);
    }

    #[Route('/MyRegistration', name:'app_myRegistration')]
    public function myRegistration(Request $request, InscriptionRepository $inscriptionRepository, EvenementRepository $evenementRepository): Response 
    {
        $user = $this->getUser();
        $inscriptions = $inscriptionRepository->findBy(['user' => $user]);
        $evenements = [];

        foreach ( $inscriptions as $inscription) {
            $evenements[] = $inscription->getEvenementId();
        }     


        usort($evenements, function ($a, $b) {
            return $a->getDateDebut() <=> $b->getDateDebut();
        });

        return $this->render('home/myRegistration.html.twig', [
            'inscriptions' => $inscriptions,
            'evenements' => $evenements,
        ]);
    }

}

templates/home/editEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}EventLinker ShowEvent{% endblock %}

{% set routeName = app.request.attributes.get('_route') %}
{% block body %}

{% for message in app.flashes('success') %}
<div class="container">
    <div class=" alert alert-success d-flex justify-content-center my-2"> 
        {{ message}}
    </div>                
</div>
{% endfor %}
{% for message in app.flashes('danger') %}
<div class="container">
    <div class=" alert alert-danger d-flex justify-content-center my-2"> 
        {{ message}}
    </div>                
</div>
{% endfor %}

<a href="{{ path(previousRouteName, { 'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-secondary m-2">Retour</a>
<div class="container my-2 m-auto card">

        <h1 class="my-2 text-center">Modifier l'événement</h1>
        {{ form_start(form) }}          
        <div class="row g-3">
            <div class="col-12">
               {{ form_row(form.nom) }}      
            </div>
            <div class="col-12">
                {{ form_row(form.description) }}                
            </div>
            <div class="col-md-6">
                {{ form_row(form.date_debut) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.date_fin) }}
            </div>
            <div class="col-12">        
                {{ form_row(form.lieux) }}
            </div>
            <div class="col-12">        
                {{ form_row(form.image) }}
            </div>
            <div class="col-12 text-end">
                {{ form_row(form.submit) }}
            </div>
            {{ form_row(form.id_createur) }}    
        </div>                    
        {{ form_end(form) }}            



</div>


{% endblock %}
 

templates/home/eventMaker.html.twig
{% extends 'base.html.twig' %}

{% block title %}EventLinker CreateEvent{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
    <div class="container">
        <div class=" alert alert-success d-flex justify-content-center my-2"> 
            {{ message}}
        </div>                
    </div>
    {% endfor %}
    {% for message in app.flashes('danger') %}
    <div class="container">
        <div class=" alert alert-danger d-flex justify-content-center my-2"> 
            {{ message}}
        </div>                
    </div>
    {% endfor %}
    <div class="container card m-auto my-2">
        <h2 class="my-2 text-center">Formulaire de création d'évenement</h2>

           {{ form_start(form) }}          
        <div class="row g-3">
            <div class="col-12">
               {{ form_row(form.nom) }}      
            </div>
            <div class="col-12">
                {{ form_row(form.description) }}                
            </div>
            <div class="col-md-6">
                {{ form_row(form.date_debut) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.date_fin) }}
            </div>
            <div class="col-12">        
                {{ form_row(form.lieux) }}
            </div>
            <div class="col-12">        
                {{ form_row(form.image) }}
            </div>
            <div class="col-12 text-end">
                {{ form_row(form.submit) }}
            </div>
        {{ form_end(form) }}            
        </div>


    </div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}
{% set routeName = app.request.attributes.get('_route') %}
{% block title %}Hello HomeController!{% endblock %}


{% block body %}
    {% for message in app.flashes('success') %}
    <div class="container">
        <div class=" alert alert-success d-flex justify-content-center my-2"> 
            {{ message}}
        </div>                
    </div>
    {% endfor %}
    {% for message in app.flashes('danger') %}
    <div class="container">
        <div class=" alert alert-danger d-flex justify-content-center my-2"> 
            {{ message}}
        </div>                
    </div>
    {% endfor %}
    {% if evenements is empty %}
        <div class="container m-6">
            <p>Aucun évenement pour le moment</p>
        </div>
    {% else %}
        <div class="container m-6 p-6">
            <div class="container card d-flex flex-column justify-content-evenly w-50 m-auto my-3">
                {{ form_start(dateFilterForm) }}
                {{ form_row(dateFilterForm.startDate) }}
                {{ form_row(dateFilterForm.endDate) }}
                {{ form_row(dateFilterForm.filter) }}
                {{ form_end(dateFilterForm) }}
            </div>
            <div class="row ">
                {% if filteredEvents is empty %}
                    {% for evenement in evenements %}
                        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 my-2">
                            <div class="card d-flex flex-column mb-4 text-center h-100">
                                <figure class="figure">
                                    <img src="{{ asset('uploads/images/' ~ evenement.image) }}" class="figure-img img-fluid rounded" alt="...">
                                    <figcaption class="figure-caption">du {{ evenement.dateDebut | date('d-m-Y H:i:s') }}.</figcaption>
                                    <figcaption class="figure-caption">du {{ evenement.dateFin | date('d-m-Y H:i:s') }}.</figcaption>
                                  </figure>
                                <div class="card-body d-flex flex-column  justify-content-center align-items-center p-2">
                                    <h5 class="card-title h-auto">{{ evenement.nom }}</h5>    
                                    <p class="card-text d-inline-block flex-grow-1">{{ evenement.description }}</p> 
                                    <div class="container d-flex justify-content-evenly align-items-center ">
                                        <a href="{{ path('app_showEvent', { 'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-info">Lire la suite</a>                                
                                        {% if app.user %}
                                            {% if isUserRegistered(app.user, evenement) %}
                                                <a href="{{ path('app_evenement_unregister', {'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-danger">Se désinscrire</a>
                                            {% else %}
                                                <a href="{{ path('app_evenement_register', {'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-success">S'inscrire</a>
                                            {% endif %} 
                                        {% else %}
                                                <a href="{{ path('app_login') }}" class="btn btn-primary">Se connecter</a>
                                        {% endif %}                            
                                    </div>
                                </div>
                            </div>            
                        </div>
                    {% endfor %}   
                {% else %}
                {% for evenement in filteredEvents %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 my-2">
                    <div class="card d-flex flex-column mb-4 text-center h-100">
                        <figure class="figure">
                            <img src="{{ asset('uploads/images/' ~ evenement.image) }}" class="figure-img img-fluid rounded" alt="...">
                            <figcaption class="figure-caption">du {{ evenement.dateDebut | date('d-m-Y H:i:s') }}.</figcaption>
                            <figcaption class="figure-caption">du {{ evenement.dateFin | date('d-m-Y H:i:s') }}.</figcaption>
                          </figure>
                        <div class="card-body d-flex flex-column  justify-content-center align-items-center p-2">
                            <h5 class="card-title h-auto">{{ evenement.nom }}</h5>    
                            <p class="card-text d-inline-block flex-grow-1">{{ evenement.description }}</p> 
                            <div class="container d-flex justify-content-evenly align-items-center ">
                                <a href="{{ path('app_showEvent', { 'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-info">Lire la suite</a>                                
                                {% if app.user %}
                                    {% if isUserRegistered(app.user, evenement) %}
                                        <a href="{{ path('app_evenement_unregister', {'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-danger">Se désinscrire</a>
                                    {% else %}
                                        <a href="{{ path('app_evenement_register', {'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-success">S'inscrire</a>
                                    {% endif %} 
                                {% else %}
                                        <a href="{{ path('app_login') }}" class="btn btn-primary">Se connecter</a>
                                {% endif %}                            
                            </div>
                        </div>
                    </div>            
                </div>
            {% endfor %}    
        {% endif %}
        </div>
        </div>
    {% endif %}
{% endblock %}

templates/home/myRegistration.html.twig
{% extends 'base.html.twig' %}
{% set routeName = app.request.attributes.get('_route') %}
{% block title %}Hello HomeController!{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
    <div class="container">
        <div class=" alert alert-success d-flex justify-content-center my-2"> 
            {{ message}}
        </div>                
    </div>
    {% endfor %}
    {% for message in app.flashes('danger') %}
    <div class="container">
        <div class=" alert alert-danger d-flex justify-content-center my-2"> 
            {{ message}}
        </div>                
    </div>
    {% endfor %}
    {% if evenements is empty %}
        <div class="container d-flex justify-content-center align-items-center h-100vh m-6">
            <p>Aucune inscription à des évenement</p>
        </div>
    {% else %}
        <div class="container m-6 p-6">
            <div class="row">
                
                {% for evenement in evenements %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 my-2">
                    <div class="card d-flex flex-column mb-4 text-center h-100">
                        <figure class="figure">
                            <img src="{{ asset('uploads/images/' ~ evenement.image) }}" class="figure-img img-fluid rounded" alt="...">
                            <figcaption class="figure-caption">du {{ evenement.dateDebut | date('d-m-Y H:i:s') }}.</figcaption>
                            <figcaption class="figure-caption">du {{ evenement.dateFin | date('d-m-Y H:i:s') }}.</figcaption>
                          </figure>
                        <div class="card-body d-flex flex-column  justify-content-center align-items-center p-2">
                            <h5 class="card-title h-auto">{{ evenement.nom }}</h5>    
                            <p class="card-text d-inline-block flex-grow-1">{{ evenement.description }}</p> 
                            <div class="container d-flex justify-content-evenly align-items-center ">
                                <a href="{{ path('app_showEvent', { 'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-info">Lire la suite</a>                                
                                {% if app.user %}
                                    {% if isUserRegistered(app.user, evenement) %}
                                        <a href="{{ path('app_evenement_unregister', {'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-danger">Se désinscrire</a>
                                    {% else %}
                                        <a href="{{ path('app_evenement_register', {'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-success">S'inscrire</a>
                                    {% endif %} 
                                {% else %}
                                        <a href="{{ path('app_login') }}" class="btn btn-primary">Se connecter</a>
                                {% endif %}                            
                            </div>
                        </div>
                    </div>            
                </div>
            {% endfor %}                
            </div>
        </div>
    {% endif %}

{% endblock %}

templates/home/showEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}EventLinker ShowEvent{% endblock %}

{% set routeName = app.request.attributes.get('_route') %}
{% block body %}
{% for message in app.flashes('success') %}
<div class="container">
    <div class=" alert alert-success d-flex justify-content-center my-2"> 
        {{ message}}
    </div>                
</div>
{% endfor %}
{% for message in app.flashes('danger') %}
<div class="container">
    <div class=" alert alert-danger d-flex justify-content-center my-2"> 
        {{ message}}
    </div>                
</div>
{% endfor %}
<div class="m-2">
    <a href="{{ path(previousRouteName, { 'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-secondary">Retour</a>
    {% if app.user == evenement.idcreateur%}
    <a href="{{ path('app_editEvent', { 'evenementId': evenement.id, 'routeName': routeName}) }}" class="btn btn-primary">Modifier</a>    
    <a href="{{ path('app_deleteEvent', { 'evenementId': evenement.id, 'routeName': previousRouteName}) }}" class="btn btn-danger">Supprimer</a>
    {% endif %}    
</div>
<div class="container card my-2 m-auto">
    <p class="fs-6 text text-start">{{ evenement.dateDebut | date('d-m-Y H:i:s') }} - {{ evenement.dateFin | date('d-m-Y H:i:s') }}.</p>
    <h5 class="card-title text-center">{{ evenement.nom }}</h5>      
    <div class="container d-flex flex-column justify-content-center align-items-center m-3">
        <img src="{{ asset('uploads/images/' ~ evenement.image) }}" class="object-fit-contain"  alt="photo indisponible">
        <p class="card-text">{{ evenement.description }}</p> 
    </div>    
</div>



{% endblock %}